export interface listaReclamosInterface {
    id: number,
    reclamo: number,
    fecha: string,
    fechaCompra: string,
    tipoDoc: string,
    docNro: string,
    apellidos: string,
    nombres: string,
    seccion: any,
    prodCodBar: string,
    prodDescripcion: string,
    cantidad: number,
    motivo: string,
    idEmp: string,
    prometidoDia: string,
    turno: string,
    importe: number,
    solucion: string,
    tipo: string,
    estado: string,
    fechaSol: string,
    costo: number,
    taller: string,
    observaciones: string,
    pagado: string,
    ticket: number,
    ncred: string,
    nroTransferInt: null,
    idTipo: number,
    tipoRec: string,
    grupoRec: string,
    cerrado: string,
    expr1: string,
    empresa: string
  }
  